const bachGroups={"Medo":["Mimulus","Rock Rose","Aspen","Cherry Plum","Red Chestnut"],"Incerteza e insegurança":["Cerato","Scleranthus","Hornbeam","Gentian","Gorse","Wild Oat"],"Falta de interesse no presente":["Clematis","Honeysuckle","Wild Rose","Olive","White Chestnut","Mustard","Chestnut Bud"],"Solidão":["Water Violet","Impatiens","Heather"],"Hipersensibilidade a influências e ideias externas":["Agrimony","Centaury","Walnut","Holly"],"Desespero":["Larch","Pine","Elm","Sweet Chestnut","Star of Bethlehem","Willow","Oak","Crab Apple"],"Cuidado excessivo com os outros":["Chicory","Vervain","Vine","Beech","Rock Water"]};
const bachDescriptions={"Mimulus":"medos conhecidos; coragem diante de situações concretas","Rock Rose":"terror ou pânico; coragem em situações extremas","Aspen":"medos vagos; confiança diante do desconhecido","Cherry Plum":"medo de perder o controle; serenidade e autocontrole","Red Chestnut":"preocupação excessiva com pessoas queridas; confiança","Cerato":"dúvida das próprias decisões; confiança na percepção pessoal","Scleranthus":"indecisão; equilíbrio e decisão","Hornbeam":"cansaço mental para começar; disposição","Gentian":"desânimo após contratempos; perseverança","Gorse":"desesperança; esperança","Wild Oat":"incerteza de direção; clareza de propósito","Clematis":"distração e fuga do presente; presença","Honeysuckle":"apego ao passado; abertura ao presente","Wild Rose":"apatia e resignação; interesse pela vida","Olive":"exaustão; renovação","White Chestnut":"pensamentos repetitivos; tranquilidade mental","Mustard":"tristeza sem causa aparente; estabilidade emocional","Chestnut Bud":"repetição de padrões; aprendizado com a experiência","Water Violet":"isolamento e reserva; conexão com autonomia","Impatiens":"impaciência; tolerância e calma","Heather":"necessidade excessiva de atenção; escuta e interesse pelo outro","Agrimony":"sofrimento escondido; autenticidade","Centaury":"dificuldade de dizer não; limites","Walnut":"transições e influências externas; adaptação e proteção","Holly":"ciúme, raiva ou suspeita; abertura afetiva","Larch":"falta de confiança; autoconfiança","Pine":"culpa; autoaceitação","Elm":"sobrecarga; confiança na própria capacidade","Sweet Chestnut":"angústia extrema; esperança e transformação","Star of Bethlehem":"choque ou trauma; consolo e integração","Willow":"ressentimento; atitude construtiva","Oak":"persistência além dos limites; permissão para descansar","Crab Apple":"vergonha ou rejeição de si; aceitação","Chicory":"cuidado possessivo; afeto sem cobrança","Vervain":"excesso de entusiasmo e tensão; moderação","Vine":"dominação; liderança respeitosa","Beech":"crítica e intolerância; compreensão","Rock Water":"rigidez e autoexigência; flexibilidade"};
const oilDescriptions={"Gerânio":"equilíbrio emocional e acolhimento","Bergamota":"leveza, ânimo e relaxamento","Alecrim":"atenção, disposição e clareza","Rosa":"afeto e conforto emocional","Tea Tree":"limpeza e purificação aromática","Lavanda":"relaxamento e serenidade","Esclareia":"relaxamento e equilíbrio emocional","Canela":"vitalidade e aconchego","Anis Estrelado":"conforto e acolhimento","Laranja":"leveza e relaxamento","Ylang Ylang":"relaxamento e sensualidade","Cedro":"centramento e estabilidade","Artemísia":"introspecção e contemplação","Pimenta Rosa":"energia e movimento","Olíbano":"meditação e centramento","Hortelã Pimenta":"frescor e atenção","Melaleuca":"limpeza aromática","Limão":"frescor e clareza","Eucalipto":"frescor e ambiente revigorante","Camomila":"tranquilidade e conforto","Sândalo":"serenidade e centramento","Copaíba":"acolhimento e relaxamento","Sálvia":"clareza e renovação","Grapefruit":"leveza e ânimo","Lemongrass":"energia e renovação do ambiente","Manjericão":"foco e disposição","Patchouli":"aterramento e estabilidade","Tomilho":"vigor e fortalecimento","Erva Doce":"conforto e suavidade","Pinho":"frescor e vitalidade","Gengibre":"energia e aquecimento sensorial","Jasmim":"confiança e sensualidade","Vetiver":"aterramento e desaceleração"};
const tarotSource="Clube do Tarô — https://www.clubedotaro.com.br/site/p55_1painel_tempo.asp";
const tarotCards=["O Louco","I. O Mago","II. A Papisa","III. A Imperatriz","IV. O Imperador","V. O Papa","VI. O Enamorado","VII. O Carro","VIII. A Justiça","IX. O Eremita","X. A Roda da Fortuna","XI. A Força","XII. O Pendurado","XIII. A Morte","XIV. A Temperança","XV. O Diabo","XVI. A Torre","XVII. A Estrela","XVIII. A Lua","XIX. O Sol","XX. O Julgamento","XXI. O Mundo","Outro"];
const tarotDescriptions={
"O Louco":"Representa deslocamento, liberdade e abertura ao desconhecido. Pode indicar um momento em que a pessoa se move sem garantias, guiada mais pela experiência e pela disponibilidade para o novo do que por um plano rígido. Na leitura, chama atenção para espontaneidade, desapego de estruturas e também para a necessidade de perceber riscos antes de avançar.",
"I. O Mago":"Relaciona-se à iniciativa, habilidade e capacidade de mobilizar recursos disponíveis. O Mago sugere ação consciente, começo de processo e possibilidade de interferir no rumo dos acontecimentos por meio de intenção, técnica e presença. Também convida a distinguir potência real de dispersão ou excesso de confiança.",
"II. A Papisa":"Associa-se à interiorização, estabilidade e conhecimento silencioso. É uma carta de maturação, observação e escuta interna, indicando que nem tudo precisa ser exposto ou resolvido de imediato. Pode sugerir tempo de espera fértil, aprofundamento e confiança em processos que ainda não se tornaram visíveis.",
"III. A Imperatriz":"Expressa criatividade, desenvolvimento e capacidade de fazer crescer. Pode apontar para comunicação, fertilidade de ideias, expansão e manifestação no mundo concreto. Em contextos afetivos, sugere presença, expressão e nutrição do vínculo, com atenção para não transformar cuidado em excesso de controle.",
"IV. O Imperador":"Representa estrutura, autoridade, sustentação e estabilidade. Indica necessidade de organização, limites claros e base concreta para que algo se mantenha. Pode simbolizar segurança e capacidade de decisão, mas também pede atenção à rigidez, à necessidade excessiva de controle ou à dificuldade de ceder.",
"V. O Papa":"Liga-se a valores, orientação, transmissão de conhecimento e busca de referência. Pode indicar aconselhamento, tradição, aprendizado ou necessidade de alinhar escolhas a princípios mais amplos. Também convida a examinar até que ponto regras e crenças herdadas ajudam ou limitam o processo atual.",
"VI. O Enamorado":"É um arcano de escolha, vínculo e livre-arbítrio. Em geral, coloca a pessoa diante de desejos, afetos e caminhos possíveis que exigem posicionamento. Pode falar de atração, harmonia e encontro, mas sobretudo da responsabilidade de escolher conscientemente e assumir as consequências da decisão.",
"VII. O Carro":"Relaciona-se a movimento, avanço e condução. Mostra energia direcionada para sair de uma condição e chegar a outra, sugerindo decisão, dinamismo e capacidade de assumir as rédeas do processo. Pode também apontar para pressa ou necessidade de alinhar forças internas antes de acelerar.",
"VIII. A Justiça":"Representa equilíbrio, medida, responsabilidade e avaliação. Convida a olhar fatos, escolhas e consequências com clareza, buscando proporcionalidade e coerência. Em processos relacionais, pode indicar necessidade de limites, acordos, reparação ou compreensão mais objetiva daquilo que cabe a cada parte.",
"IX. O Eremita":"Associa-se à prudência, concentração, maturidade e busca interior. Indica um ritmo mais lento, de recolhimento e investigação, no qual a resposta pode surgir do silêncio e da experiência acumulada. Pode sugerir necessidade de distância temporária, reflexão e menor dependência de validação externa.",
"X. A Roda da Fortuna":"Fala de mudança de ciclo, movimento e alternância. Lembra que certos acontecimentos obedecem a ritmos maiores do que a vontade individual e que posições podem se modificar rapidamente. Pode indicar oportunidade de mudança, reviravolta ou necessidade de adaptação a uma fase que já está se transformando.",
"XI. A Força":"Relaciona-se à coragem, firmeza e domínio consciente dos impulsos. Sua potência não é apenas física: trata-se de conduzir energia intensa sem violência, usando presença, constância e autocontrole. Pode indicar capacidade de atravessar conflitos internos com maturidade, evitando repressão ou explosão.",
"XII. O Pendurado":"Representa pausa, prova, suspensão e mudança de perspectiva. Pode indicar um momento em que avançar pela força não produz resultado e é necessário observar a situação de outro ângulo. A carta sugere entrega consciente, revisão de prioridades e aceitação temporária de uma condição para que algo possa ser compreendido.",
"XIII. A Morte":"É um arcano de transformação, encerramento e renovação. Não precisa ser lido de forma literal: simboliza o corte com uma forma anterior que já perdeu função, abrindo espaço para outra configuração. Em processos afetivos, pode apontar para luto, desapego e necessidade de permitir que um ciclo termine de fato.",
"XIV. A Temperança":"Associa-se à moderação, integração, conciliação e circulação. Sugere equilíbrio construído gradualmente, por meio de ajustes, trocas e combinação de elementos diferentes. Pode indicar cura simbólica, diálogo e reorganização, evitando tanto a pressa quanto a estagnação.",
"XV. O Diabo":"Relaciona-se a desejo, sedução, vínculos, tentações e forças que exercem fascínio. Pode revelar a intensidade de apegos, compulsões, dependências ou interesses que dificultam escolhas livres. A leitura convida a reconhecer o que prende, atrai ou manipula para recuperar consciência sobre o próprio poder de decisão.",
"XVI. A Torre":"Representa ruptura, queda de estruturas e reorganização forçada. Pode indicar acontecimentos ou compreensões que desmontam uma construção anterior, especialmente quando ela já não se sustenta. Apesar do impacto, também abre espaço para reconstrução mais realista, depois que ilusões ou bases frágeis são expostas.",
"XVII. A Estrela":"Fala de esperança, inspiração, confiança e abertura. Sugere um estado de maior transparência e receptividade, no qual a pessoa pode retomar contato com aquilo que orienta e dá sentido. Também indica delicadeza, renovação e disposição para seguir sem precisar controlar cada etapa do caminho.",
"XVIII. A Lua":"Relaciona-se à sensibilidade, imaginação, ciclos e zonas pouco claras. Pode evidenciar medos, projeções, intuições, fantasias e conteúdos emocionais que ainda não foram totalmente compreendidos. A carta pede atenção ao que é percebido subjetivamente e cautela antes de transformar impressão em certeza.",
"XIX. O Sol":"Representa clareza, vitalidade, expressão e visibilidade. Pode indicar expansão, confiança, comunicação mais aberta e possibilidade de enxergar uma situação com menos ambiguidade. Em vínculos, favorece a ideia de verdade exposta, reconhecimento e energia disponível para uma etapa mais consciente.",
"XX. O Julgamento":"Associa-se à avaliação, tomada de consciência e chamado para um novo posicionamento. Pode representar balanço de escolhas anteriores, compreensão do que precisa ser revisto e decisão de responder de modo diferente. É um arcano de despertar, reconhecimento e fechamento de contas internas antes de uma nova fase.",
"XXI. O Mundo":"Representa integração, totalidade e conclusão de ciclo. Sugere compreensão mais ampla do percurso, sensação de fechamento e possibilidade de ocupar um lugar mais inteiro diante da experiência vivida. Pode indicar realização, síntese e passagem para uma nova etapa com maior consciência do que foi aprendido."
};
